# Generated by Django 5.2.1 on 2025-05-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('release_date', models.DateField()),
                ('genres', models.JSONField()),
                ('keywords', models.JSONField()),
                ('cast', models.JSONField()),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
